select * from customer;

select * from address;

select FIRST_NAME,LAST_NAME, address,phone
from CUSTOMER join ADDRESS
on CUSTOMER.ADDRESS_ID= ADDRESS.ADDRESS_ID;

-- to get the people with null values I add left join
select FIRST_NAME, LAST_NAME, c.address_id,address,PHONE
from CUSTOMER c left join  ADDRESS A on c.ADDRESS_ID = a.ADDRESS_ID;

SELECT FIRST_NAME,LAST_NAME,C.ADDRESS_ID,A.ADDRESS_ID,ADDRESS,PHONE FROM CUSTOMER C RIGHT JOIN ADDRESS A
ON C.ADDRESS_ID= A.ADDRESS_ID;

--FULL JOİN
SELECT FIRST_NAME,LAST_NAME,C.ADDRESS_ID,A.ADDRESS_ID,ADDRESS,PHONE FROM CUSTOMER C FULL JOIN ADDRESS A
ON C.ADDRESS_ID= A.ADDRESS_ID;