--GET ME FİRST_NAME,LAST_NAME AND DEPARTMENT NAME FOR ALL EMPLOYEES

SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;

SELECT FIRST_NAME,LAST_NAME ,DEPARTMENT_NAME FROM EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID ;

SELECT FIRST_NAME,LAST_NAME ,DEPARTMENT_NAME FROM EMPLOYEES E
                                                      LEFT JOIN DEPARTMENTS D ON D.DEPARTMENT_ID = E.DEPARTMENT_ID WHERE E.DEPARTMENT_ID IS NULL ;
--GET ME FİRST NAME , LAST_NAME AND DEPARTMENT_NAME, CİTY FOR ALL EMPLOYEES
SELECT FIRST_NAME,LAST_NAME , DEPARTMENT_NAME,city e from EMPLOYEES
e join DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID join LOCATIONS l on d.LOCATION_ID = l.LOCATION_ID;

--get me first name ,last name and department name ,city ,country name for all employees
SELECT FIRST_NAME,LAST_NAME , DEPARTMENT_NAME,city e from EMPLOYEES
                                                              e join DEPARTMENTS d on e.DEPARTMENT_ID = d.DEPARTMENT_ID join LOCATIONS l on d.LOCATION_ID = l.LOCATION_ID
join COUNTRIES c on c.COUNTRY_ID= l.COUNTRY_ID;

