select * from SCRUMTEAM;

--adding new column
ALTER TABLE SCRUMTEAM ADD salary INTEGER;
--update existig salary
update SCRUMTEAM
SET salary = 100000 where EMP_ID= 3;
update SCRUMTEAM SET salary =10000 where emp_id=3;
update SCRUMTEAM set salary= 12000 where emp_id=4;
update SCRUMTEAM set salary= 90000 where EMP_ID=5;

--RENAME THE COLUMN
ALTER TABLE SCRUMTEAM RENAME COLUMN SALARY TO ANNUAL_SALARY;

--DELETE, DROP COLUMN
ALTER TABLE SCRUMTEAM DROP COLUMN ANNUAL_SALARY;

--HOW TO CHANGE TABLE NAME?
ALTER TABLE SCRUMTEAM RENAME TO AGILETEAM;

SELECT  * FROM AGILETEAM;

COMMIT;
--İF WE WANT TO DELETE THE TABLE AD DATA TOGETHER
TRUNCATE TABLE AGILETEAM;

--İF WE WANT TO DELETE THE TABLE AND DATA TOGETHER
DROP TABLE  AGILETEAM;






